/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedMinhaAgendaRouteImport } from './routes/_authenticated/minha-agenda'
import { Route as AuthenticatedMeusTreinosRouteImport } from './routes/_authenticated/meus-treinos'
import { Route as AuthenticatedMeusPagamentosRouteImport } from './routes/_authenticated/meus-pagamentos'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedExerciciosRouteImport } from './routes/_authenticated/exercicios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAlunosIndexRouteImport } from './routes/_authenticated/alunos.index'
import { Route as AuthenticatedAlunosNovoRouteImport } from './routes/_authenticated/alunos.novo'
import { Route as AuthenticatedAlunosIdRouteImport } from './routes/_authenticated/alunos.$id'
import { Route as AuthenticatedAdminCustomizacaoRouteImport } from './routes/_authenticated/admin.customizacao'
import { Route as AuthenticatedAlunosIdIndexRouteImport } from './routes/_authenticated/alunos.$id.index'
import { Route as ApiPublicHooksLembreteVencimentoRouteImport } from './routes/api/public/hooks/lembrete-vencimento'
import { Route as AuthenticatedAlunosIdNutricaoRouteImport } from './routes/_authenticated/alunos.$id.nutricao'
import { Route as AuthenticatedAlunosIdMetasRouteImport } from './routes/_authenticated/alunos.$id.metas'
import { Route as AuthenticatedAlunosIdFotosRouteImport } from './routes/_authenticated/alunos.$id.fotos'
import { Route as AuthenticatedAlunosIdEvolucaoRouteImport } from './routes/_authenticated/alunos.$id.evolucao'
import { Route as AuthenticatedAlunosIdAnamneseRouteImport } from './routes/_authenticated/alunos.$id.anamnese'
import { Route as AuthenticatedAlunosIdTreinosIndexRouteImport } from './routes/_authenticated/alunos.$id.treinos.index'
import { Route as AuthenticatedAlunosIdAvaliacoesIndexRouteImport } from './routes/_authenticated/alunos.$id.avaliacoes.index'
import { Route as AuthenticatedAlunosIdTreinosTreinoIdRouteImport } from './routes/_authenticated/alunos.$id.treinos.$treinoId'
import { Route as AuthenticatedAlunosIdAvaliacoesNovaRouteImport } from './routes/_authenticated/alunos.$id.avaliacoes.nova'
import { Route as AuthenticatedAlunosIdAvaliacoesAvalIdRouteImport } from './routes/_authenticated/alunos.$id.avaliacoes.$avalId'
import { Route as AuthenticatedAlunosIdTreinosTreinoIdExecutarRouteImport } from './routes/_authenticated/alunos.$id.treinos.$treinoId.executar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaAgendaRoute =
  AuthenticatedMinhaAgendaRouteImport.update({
    id: '/minha-agenda',
    path: '/minha-agenda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusTreinosRoute =
  AuthenticatedMeusTreinosRouteImport.update({
    id: '/meus-treinos',
    path: '/meus-treinos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusPagamentosRoute =
  AuthenticatedMeusPagamentosRouteImport.update({
    id: '/meus-pagamentos',
    path: '/meus-pagamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExerciciosRoute = AuthenticatedExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunosIndexRoute =
  AuthenticatedAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlunosNovoRoute = AuthenticatedAlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunosIdRoute = AuthenticatedAlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCustomizacaoRoute =
  AuthenticatedAdminCustomizacaoRouteImport.update({
    id: '/admin/customizacao',
    path: '/admin/customizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlunosIdIndexRoute =
  AuthenticatedAlunosIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const ApiPublicHooksLembreteVencimentoRoute =
  ApiPublicHooksLembreteVencimentoRouteImport.update({
    id: '/api/public/hooks/lembrete-vencimento',
    path: '/api/public/hooks/lembrete-vencimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAlunosIdNutricaoRoute =
  AuthenticatedAlunosIdNutricaoRouteImport.update({
    id: '/nutricao',
    path: '/nutricao',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdMetasRoute =
  AuthenticatedAlunosIdMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdFotosRoute =
  AuthenticatedAlunosIdFotosRouteImport.update({
    id: '/fotos',
    path: '/fotos',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdEvolucaoRoute =
  AuthenticatedAlunosIdEvolucaoRouteImport.update({
    id: '/evolucao',
    path: '/evolucao',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdAnamneseRoute =
  AuthenticatedAlunosIdAnamneseRouteImport.update({
    id: '/anamnese',
    path: '/anamnese',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdTreinosIndexRoute =
  AuthenticatedAlunosIdTreinosIndexRouteImport.update({
    id: '/treinos/',
    path: '/treinos/',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdAvaliacoesIndexRoute =
  AuthenticatedAlunosIdAvaliacoesIndexRouteImport.update({
    id: '/avaliacoes/',
    path: '/avaliacoes/',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdTreinosTreinoIdRoute =
  AuthenticatedAlunosIdTreinosTreinoIdRouteImport.update({
    id: '/treinos/$treinoId',
    path: '/treinos/$treinoId',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdAvaliacoesNovaRoute =
  AuthenticatedAlunosIdAvaliacoesNovaRouteImport.update({
    id: '/avaliacoes/nova',
    path: '/avaliacoes/nova',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdAvaliacoesAvalIdRoute =
  AuthenticatedAlunosIdAvaliacoesAvalIdRouteImport.update({
    id: '/avaliacoes/$avalId',
    path: '/avaliacoes/$avalId',
    getParentRoute: () => AuthenticatedAlunosIdRoute,
  } as any)
const AuthenticatedAlunosIdTreinosTreinoIdExecutarRoute =
  AuthenticatedAlunosIdTreinosTreinoIdExecutarRouteImport.update({
    id: '/executar',
    path: '/executar',
    getParentRoute: () => AuthenticatedAlunosIdTreinosTreinoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercicios': typeof AuthenticatedExerciciosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/meus-pagamentos': typeof AuthenticatedMeusPagamentosRoute
  '/meus-treinos': typeof AuthenticatedMeusTreinosRoute
  '/minha-agenda': typeof AuthenticatedMinhaAgendaRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/admin/customizacao': typeof AuthenticatedAdminCustomizacaoRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRouteWithChildren
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/alunos/$id/anamnese': typeof AuthenticatedAlunosIdAnamneseRoute
  '/alunos/$id/evolucao': typeof AuthenticatedAlunosIdEvolucaoRoute
  '/alunos/$id/fotos': typeof AuthenticatedAlunosIdFotosRoute
  '/alunos/$id/metas': typeof AuthenticatedAlunosIdMetasRoute
  '/alunos/$id/nutricao': typeof AuthenticatedAlunosIdNutricaoRoute
  '/api/public/hooks/lembrete-vencimento': typeof ApiPublicHooksLembreteVencimentoRoute
  '/alunos/$id/': typeof AuthenticatedAlunosIdIndexRoute
  '/alunos/$id/avaliacoes/$avalId': typeof AuthenticatedAlunosIdAvaliacoesAvalIdRoute
  '/alunos/$id/avaliacoes/nova': typeof AuthenticatedAlunosIdAvaliacoesNovaRoute
  '/alunos/$id/treinos/$treinoId': typeof AuthenticatedAlunosIdTreinosTreinoIdRouteWithChildren
  '/alunos/$id/avaliacoes/': typeof AuthenticatedAlunosIdAvaliacoesIndexRoute
  '/alunos/$id/treinos/': typeof AuthenticatedAlunosIdTreinosIndexRoute
  '/alunos/$id/treinos/$treinoId/executar': typeof AuthenticatedAlunosIdTreinosTreinoIdExecutarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercicios': typeof AuthenticatedExerciciosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/meus-pagamentos': typeof AuthenticatedMeusPagamentosRoute
  '/meus-treinos': typeof AuthenticatedMeusTreinosRoute
  '/minha-agenda': typeof AuthenticatedMinhaAgendaRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/admin/customizacao': typeof AuthenticatedAdminCustomizacaoRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/alunos': typeof AuthenticatedAlunosIndexRoute
  '/alunos/$id/anamnese': typeof AuthenticatedAlunosIdAnamneseRoute
  '/alunos/$id/evolucao': typeof AuthenticatedAlunosIdEvolucaoRoute
  '/alunos/$id/fotos': typeof AuthenticatedAlunosIdFotosRoute
  '/alunos/$id/metas': typeof AuthenticatedAlunosIdMetasRoute
  '/alunos/$id/nutricao': typeof AuthenticatedAlunosIdNutricaoRoute
  '/api/public/hooks/lembrete-vencimento': typeof ApiPublicHooksLembreteVencimentoRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdIndexRoute
  '/alunos/$id/avaliacoes/$avalId': typeof AuthenticatedAlunosIdAvaliacoesAvalIdRoute
  '/alunos/$id/avaliacoes/nova': typeof AuthenticatedAlunosIdAvaliacoesNovaRoute
  '/alunos/$id/treinos/$treinoId': typeof AuthenticatedAlunosIdTreinosTreinoIdRouteWithChildren
  '/alunos/$id/avaliacoes': typeof AuthenticatedAlunosIdAvaliacoesIndexRoute
  '/alunos/$id/treinos': typeof AuthenticatedAlunosIdTreinosIndexRoute
  '/alunos/$id/treinos/$treinoId/executar': typeof AuthenticatedAlunosIdTreinosTreinoIdExecutarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercicios': typeof AuthenticatedExerciciosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/meus-pagamentos': typeof AuthenticatedMeusPagamentosRoute
  '/_authenticated/meus-treinos': typeof AuthenticatedMeusTreinosRoute
  '/_authenticated/minha-agenda': typeof AuthenticatedMinhaAgendaRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/admin/customizacao': typeof AuthenticatedAdminCustomizacaoRoute
  '/_authenticated/alunos/$id': typeof AuthenticatedAlunosIdRouteWithChildren
  '/_authenticated/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/_authenticated/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/_authenticated/alunos/$id/anamnese': typeof AuthenticatedAlunosIdAnamneseRoute
  '/_authenticated/alunos/$id/evolucao': typeof AuthenticatedAlunosIdEvolucaoRoute
  '/_authenticated/alunos/$id/fotos': typeof AuthenticatedAlunosIdFotosRoute
  '/_authenticated/alunos/$id/metas': typeof AuthenticatedAlunosIdMetasRoute
  '/_authenticated/alunos/$id/nutricao': typeof AuthenticatedAlunosIdNutricaoRoute
  '/api/public/hooks/lembrete-vencimento': typeof ApiPublicHooksLembreteVencimentoRoute
  '/_authenticated/alunos/$id/': typeof AuthenticatedAlunosIdIndexRoute
  '/_authenticated/alunos/$id/avaliacoes/$avalId': typeof AuthenticatedAlunosIdAvaliacoesAvalIdRoute
  '/_authenticated/alunos/$id/avaliacoes/nova': typeof AuthenticatedAlunosIdAvaliacoesNovaRoute
  '/_authenticated/alunos/$id/treinos/$treinoId': typeof AuthenticatedAlunosIdTreinosTreinoIdRouteWithChildren
  '/_authenticated/alunos/$id/avaliacoes/': typeof AuthenticatedAlunosIdAvaliacoesIndexRoute
  '/_authenticated/alunos/$id/treinos/': typeof AuthenticatedAlunosIdTreinosIndexRoute
  '/_authenticated/alunos/$id/treinos/$treinoId/executar': typeof AuthenticatedAlunosIdTreinosTreinoIdExecutarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/dashboard'
    | '/exercicios'
    | '/financeiro'
    | '/mensagens'
    | '/meus-pagamentos'
    | '/meus-treinos'
    | '/minha-agenda'
    | '/permissoes'
    | '/admin/customizacao'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/alunos/'
    | '/alunos/$id/anamnese'
    | '/alunos/$id/evolucao'
    | '/alunos/$id/fotos'
    | '/alunos/$id/metas'
    | '/alunos/$id/nutricao'
    | '/api/public/hooks/lembrete-vencimento'
    | '/alunos/$id/'
    | '/alunos/$id/avaliacoes/$avalId'
    | '/alunos/$id/avaliacoes/nova'
    | '/alunos/$id/treinos/$treinoId'
    | '/alunos/$id/avaliacoes/'
    | '/alunos/$id/treinos/'
    | '/alunos/$id/treinos/$treinoId/executar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/dashboard'
    | '/exercicios'
    | '/financeiro'
    | '/mensagens'
    | '/meus-pagamentos'
    | '/meus-treinos'
    | '/minha-agenda'
    | '/permissoes'
    | '/admin/customizacao'
    | '/alunos/novo'
    | '/alunos'
    | '/alunos/$id/anamnese'
    | '/alunos/$id/evolucao'
    | '/alunos/$id/fotos'
    | '/alunos/$id/metas'
    | '/alunos/$id/nutricao'
    | '/api/public/hooks/lembrete-vencimento'
    | '/alunos/$id'
    | '/alunos/$id/avaliacoes/$avalId'
    | '/alunos/$id/avaliacoes/nova'
    | '/alunos/$id/treinos/$treinoId'
    | '/alunos/$id/avaliacoes'
    | '/alunos/$id/treinos'
    | '/alunos/$id/treinos/$treinoId/executar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercicios'
    | '/_authenticated/financeiro'
    | '/_authenticated/mensagens'
    | '/_authenticated/meus-pagamentos'
    | '/_authenticated/meus-treinos'
    | '/_authenticated/minha-agenda'
    | '/_authenticated/permissoes'
    | '/_authenticated/admin/customizacao'
    | '/_authenticated/alunos/$id'
    | '/_authenticated/alunos/novo'
    | '/_authenticated/alunos/'
    | '/_authenticated/alunos/$id/anamnese'
    | '/_authenticated/alunos/$id/evolucao'
    | '/_authenticated/alunos/$id/fotos'
    | '/_authenticated/alunos/$id/metas'
    | '/_authenticated/alunos/$id/nutricao'
    | '/api/public/hooks/lembrete-vencimento'
    | '/_authenticated/alunos/$id/'
    | '/_authenticated/alunos/$id/avaliacoes/$avalId'
    | '/_authenticated/alunos/$id/avaliacoes/nova'
    | '/_authenticated/alunos/$id/treinos/$treinoId'
    | '/_authenticated/alunos/$id/avaliacoes/'
    | '/_authenticated/alunos/$id/treinos/'
    | '/_authenticated/alunos/$id/treinos/$treinoId/executar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksLembreteVencimentoRoute: typeof ApiPublicHooksLembreteVencimentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-agenda': {
      id: '/_authenticated/minha-agenda'
      path: '/minha-agenda'
      fullPath: '/minha-agenda'
      preLoaderRoute: typeof AuthenticatedMinhaAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-treinos': {
      id: '/_authenticated/meus-treinos'
      path: '/meus-treinos'
      fullPath: '/meus-treinos'
      preLoaderRoute: typeof AuthenticatedMeusTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-pagamentos': {
      id: '/_authenticated/meus-pagamentos'
      path: '/meus-pagamentos'
      fullPath: '/meus-pagamentos'
      preLoaderRoute: typeof AuthenticatedMeusPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercicios': {
      id: '/_authenticated/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof AuthenticatedExerciciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/': {
      id: '/_authenticated/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AuthenticatedAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/novo': {
      id: '/_authenticated/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AuthenticatedAlunosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/$id': {
      id: '/_authenticated/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AuthenticatedAlunosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/customizacao': {
      id: '/_authenticated/admin/customizacao'
      path: '/admin/customizacao'
      fullPath: '/admin/customizacao'
      preLoaderRoute: typeof AuthenticatedAdminCustomizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/$id/': {
      id: '/_authenticated/alunos/$id/'
      path: '/'
      fullPath: '/alunos/$id/'
      preLoaderRoute: typeof AuthenticatedAlunosIdIndexRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/api/public/hooks/lembrete-vencimento': {
      id: '/api/public/hooks/lembrete-vencimento'
      path: '/api/public/hooks/lembrete-vencimento'
      fullPath: '/api/public/hooks/lembrete-vencimento'
      preLoaderRoute: typeof ApiPublicHooksLembreteVencimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alunos/$id/nutricao': {
      id: '/_authenticated/alunos/$id/nutricao'
      path: '/nutricao'
      fullPath: '/alunos/$id/nutricao'
      preLoaderRoute: typeof AuthenticatedAlunosIdNutricaoRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/metas': {
      id: '/_authenticated/alunos/$id/metas'
      path: '/metas'
      fullPath: '/alunos/$id/metas'
      preLoaderRoute: typeof AuthenticatedAlunosIdMetasRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/fotos': {
      id: '/_authenticated/alunos/$id/fotos'
      path: '/fotos'
      fullPath: '/alunos/$id/fotos'
      preLoaderRoute: typeof AuthenticatedAlunosIdFotosRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/evolucao': {
      id: '/_authenticated/alunos/$id/evolucao'
      path: '/evolucao'
      fullPath: '/alunos/$id/evolucao'
      preLoaderRoute: typeof AuthenticatedAlunosIdEvolucaoRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/anamnese': {
      id: '/_authenticated/alunos/$id/anamnese'
      path: '/anamnese'
      fullPath: '/alunos/$id/anamnese'
      preLoaderRoute: typeof AuthenticatedAlunosIdAnamneseRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/treinos/': {
      id: '/_authenticated/alunos/$id/treinos/'
      path: '/treinos'
      fullPath: '/alunos/$id/treinos/'
      preLoaderRoute: typeof AuthenticatedAlunosIdTreinosIndexRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/avaliacoes/': {
      id: '/_authenticated/alunos/$id/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/alunos/$id/avaliacoes/'
      preLoaderRoute: typeof AuthenticatedAlunosIdAvaliacoesIndexRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/treinos/$treinoId': {
      id: '/_authenticated/alunos/$id/treinos/$treinoId'
      path: '/treinos/$treinoId'
      fullPath: '/alunos/$id/treinos/$treinoId'
      preLoaderRoute: typeof AuthenticatedAlunosIdTreinosTreinoIdRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/avaliacoes/nova': {
      id: '/_authenticated/alunos/$id/avaliacoes/nova'
      path: '/avaliacoes/nova'
      fullPath: '/alunos/$id/avaliacoes/nova'
      preLoaderRoute: typeof AuthenticatedAlunosIdAvaliacoesNovaRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/avaliacoes/$avalId': {
      id: '/_authenticated/alunos/$id/avaliacoes/$avalId'
      path: '/avaliacoes/$avalId'
      fullPath: '/alunos/$id/avaliacoes/$avalId'
      preLoaderRoute: typeof AuthenticatedAlunosIdAvaliacoesAvalIdRouteImport
      parentRoute: typeof AuthenticatedAlunosIdRoute
    }
    '/_authenticated/alunos/$id/treinos/$treinoId/executar': {
      id: '/_authenticated/alunos/$id/treinos/$treinoId/executar'
      path: '/executar'
      fullPath: '/alunos/$id/treinos/$treinoId/executar'
      preLoaderRoute: typeof AuthenticatedAlunosIdTreinosTreinoIdExecutarRouteImport
      parentRoute: typeof AuthenticatedAlunosIdTreinosTreinoIdRoute
    }
  }
}

interface AuthenticatedAlunosIdTreinosTreinoIdRouteChildren {
  AuthenticatedAlunosIdTreinosTreinoIdExecutarRoute: typeof AuthenticatedAlunosIdTreinosTreinoIdExecutarRoute
}

const AuthenticatedAlunosIdTreinosTreinoIdRouteChildren: AuthenticatedAlunosIdTreinosTreinoIdRouteChildren =
  {
    AuthenticatedAlunosIdTreinosTreinoIdExecutarRoute:
      AuthenticatedAlunosIdTreinosTreinoIdExecutarRoute,
  }

const AuthenticatedAlunosIdTreinosTreinoIdRouteWithChildren =
  AuthenticatedAlunosIdTreinosTreinoIdRoute._addFileChildren(
    AuthenticatedAlunosIdTreinosTreinoIdRouteChildren,
  )

interface AuthenticatedAlunosIdRouteChildren {
  AuthenticatedAlunosIdAnamneseRoute: typeof AuthenticatedAlunosIdAnamneseRoute
  AuthenticatedAlunosIdEvolucaoRoute: typeof AuthenticatedAlunosIdEvolucaoRoute
  AuthenticatedAlunosIdFotosRoute: typeof AuthenticatedAlunosIdFotosRoute
  AuthenticatedAlunosIdMetasRoute: typeof AuthenticatedAlunosIdMetasRoute
  AuthenticatedAlunosIdNutricaoRoute: typeof AuthenticatedAlunosIdNutricaoRoute
  AuthenticatedAlunosIdIndexRoute: typeof AuthenticatedAlunosIdIndexRoute
  AuthenticatedAlunosIdAvaliacoesAvalIdRoute: typeof AuthenticatedAlunosIdAvaliacoesAvalIdRoute
  AuthenticatedAlunosIdAvaliacoesNovaRoute: typeof AuthenticatedAlunosIdAvaliacoesNovaRoute
  AuthenticatedAlunosIdTreinosTreinoIdRoute: typeof AuthenticatedAlunosIdTreinosTreinoIdRouteWithChildren
  AuthenticatedAlunosIdAvaliacoesIndexRoute: typeof AuthenticatedAlunosIdAvaliacoesIndexRoute
  AuthenticatedAlunosIdTreinosIndexRoute: typeof AuthenticatedAlunosIdTreinosIndexRoute
}

const AuthenticatedAlunosIdRouteChildren: AuthenticatedAlunosIdRouteChildren = {
  AuthenticatedAlunosIdAnamneseRoute: AuthenticatedAlunosIdAnamneseRoute,
  AuthenticatedAlunosIdEvolucaoRoute: AuthenticatedAlunosIdEvolucaoRoute,
  AuthenticatedAlunosIdFotosRoute: AuthenticatedAlunosIdFotosRoute,
  AuthenticatedAlunosIdMetasRoute: AuthenticatedAlunosIdMetasRoute,
  AuthenticatedAlunosIdNutricaoRoute: AuthenticatedAlunosIdNutricaoRoute,
  AuthenticatedAlunosIdIndexRoute: AuthenticatedAlunosIdIndexRoute,
  AuthenticatedAlunosIdAvaliacoesAvalIdRoute:
    AuthenticatedAlunosIdAvaliacoesAvalIdRoute,
  AuthenticatedAlunosIdAvaliacoesNovaRoute:
    AuthenticatedAlunosIdAvaliacoesNovaRoute,
  AuthenticatedAlunosIdTreinosTreinoIdRoute:
    AuthenticatedAlunosIdTreinosTreinoIdRouteWithChildren,
  AuthenticatedAlunosIdAvaliacoesIndexRoute:
    AuthenticatedAlunosIdAvaliacoesIndexRoute,
  AuthenticatedAlunosIdTreinosIndexRoute:
    AuthenticatedAlunosIdTreinosIndexRoute,
}

const AuthenticatedAlunosIdRouteWithChildren =
  AuthenticatedAlunosIdRoute._addFileChildren(
    AuthenticatedAlunosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExerciciosRoute: typeof AuthenticatedExerciciosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedMeusPagamentosRoute: typeof AuthenticatedMeusPagamentosRoute
  AuthenticatedMeusTreinosRoute: typeof AuthenticatedMeusTreinosRoute
  AuthenticatedMinhaAgendaRoute: typeof AuthenticatedMinhaAgendaRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedAdminCustomizacaoRoute: typeof AuthenticatedAdminCustomizacaoRoute
  AuthenticatedAlunosIdRoute: typeof AuthenticatedAlunosIdRouteWithChildren
  AuthenticatedAlunosNovoRoute: typeof AuthenticatedAlunosNovoRoute
  AuthenticatedAlunosIndexRoute: typeof AuthenticatedAlunosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExerciciosRoute: AuthenticatedExerciciosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedMeusPagamentosRoute: AuthenticatedMeusPagamentosRoute,
  AuthenticatedMeusTreinosRoute: AuthenticatedMeusTreinosRoute,
  AuthenticatedMinhaAgendaRoute: AuthenticatedMinhaAgendaRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedAdminCustomizacaoRoute: AuthenticatedAdminCustomizacaoRoute,
  AuthenticatedAlunosIdRoute: AuthenticatedAlunosIdRouteWithChildren,
  AuthenticatedAlunosNovoRoute: AuthenticatedAlunosNovoRoute,
  AuthenticatedAlunosIndexRoute: AuthenticatedAlunosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksLembreteVencimentoRoute: ApiPublicHooksLembreteVencimentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
